config/routes.rb
Rails.application.routes.draw do
  get 'users/welcome'

resources :therapists

  resources :users, only: [:welcome] do
      resources :user_therapists
  end

root to: 'pages#index'
# 
# match '/user_disorders' => 'user_disorders#create', via: :post
# match '/user_disorders' => 'user_disorders#create', via: :get

get 'current_user' => "users#current_user"



  resources :disorders
  resources :user_therapists
  # resources :disorders, only: [:show] do
  #   resources :user_disorders, only: [:index]
  # end

  resources :treatments
  resources :user_disorders
  resources :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }, skip: [:sessions]
     as :user do
       get 'login' => 'devise/sessions#new', :as => :new_user_session
       post 'login' => 'devise/sessions#create', :as => :user_session
       delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
     end  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:github]

  has_many :user_therapists
  has_many :therapists, through: :therapists
  has_many  :user_disorders
  has_many  :user_disorder_treatments, through: :user_disorders
  has_many :disorders, through: :user_disorders


  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.nickname
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def welcome
    @user = current_user
    respond_to do |format|
        format.html { render :welcome}
        format.json { render json: @user }
      end
  end

  def show
    @user = User.find(params[:id])

  end

#   def current_user
#     render json: {name: current_user.name}
# end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/show.html.erb
<h1>User Show page</h1>

<% @user.disorders.uniq.each do |d| %>
  <h2><%= d.name %></h2>
  <% d.user_disorders.filter_by_user(@user).each do |dd| %>
    <p><%= dd.narrative %></p>
  <% end %>
<% end %>

app/views/users/welcome.html.erb
<h1> Hi, <%= current_user.name %>! </h1>

<p>Welcome to a community of women supporting each other with knowledge, empathy, and compassion.
  Please feel free to look around and make conenctions with other users who can help you on your
  on your journey with trauma. Remember, we all experience this journey differently, so it's
  important to be understanding of each person's process.</p>

<p> Check out the dropdown menu in the navigation bar to see the different ways other members are
  treating their trauma.</p>

  <p>If you don't know where to start, one of the most important parts of processing trauma is finding a good therapist. If you've found one that you
  can recommend, please take a minute to submit them here.</p>
  <%= link_to 'Submit Therapist', new_therapist_path, class: "btn btn-primary", id: 'therapist_button' %></li>