config/routes.rb
Rails.application.routes.draw do
  get 'users/welcome'

resources :therapists

  resources :users, only: [:welcome] do
      resources :user_therapists
  end

root to: 'pages#index'
# 
# match '/user_disorders' => 'user_disorders#create', via: :post
# match '/user_disorders' => 'user_disorders#create', via: :get

get 'current_user' => "users#current_user"



  resources :disorders
  resources :user_therapists
  # resources :disorders, only: [:show] do
  #   resources :user_disorders, only: [:index]
  # end

  resources :treatments
  resources :user_disorders
  resources :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }, skip: [:sessions]
     as :user do
       get 'login' => 'devise/sessions#new', :as => :new_user_session
       post 'login' => 'devise/sessions#create', :as => :user_session
       delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
     end  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/disorder.rb
class Disorder < ApplicationRecord
  has_many :user_disorders
  has_many :user_disorder_treatments, through: :user_disorders
  has_many :users, through: :user_disorders
  has_many :treatments, through: :user_disorder_treatments

  accepts_nested_attributes_for :user_disorders
  validates :name, presence: true

 end

app/controllers/disorders_controller.rb
require 'pry'
class DisordersController < ApplicationController
  def index
    @disorders = Disorder.all
    # @user = current_user
    respond_to do |format|
        format.html { render :index}
        format.json { render json: @disorders, include: '@user.to_json, user_disorder, user, user_disorder.user_id' }
      end
  end


  def new
    # @disorder = Disorder.new
    @disorder = Disorder.all
    # @disorder.user_disorders.build(user_id: current_user)
  end

  def create
    # @disorder = Disorder.new(disorder_params)
    @disorder = Disorder.all

     if @disorder.save
       redirect_to disorder_path(@disorder)
     else
       render :new
     end
  end

  def edit
    @disorder = Disorder.find(params[:id])
    if !@disorder.user_ids.first == current_user.id
    redirect_to users_welcome_path
  end
end

  def update
    @disorder = Disorder.find(params[:id])
    @disorder.update(disorder_params)
    redirect_to disorder_path(@disorder)
  end

  def show
    @disorder = Disorder.find(params[:id])
    @user_disorder = @disorder.user_disorders.where(user_id:current_user.id).all

    respond_to do |format|
      format.html { render :show}
      format.json { render json: @disorders }
      # format.json { render :json => {:disorder => @disorder,
      #                        :user_disorder => @user_disorder}}
    end
  end

private
  def disorder_params
    params.require(:disorder).permit(:name, :description, user_disorders_attributes: [:id, :narrative, :user_id])
  end
end

app/helpers/disorders_helper.rb
module DisordersHelper
end

app/views/disorders/_form.html.erb
<%= errors_for(@disorder) %>

<div class="field">
   <%= f.label :disorder %><br>
   <%= f.collection_select Disorder.all, :id, :name %>
 </div>



  <label>Take Control of Your Story</label>
  <%= f.fields_for :user_disorders, @disorder.user_disorders do |ff| %>
  <%= ff.text_area :narrative, size: "80%x20%" %>

  <%= ff.hidden_field :disorder_id, value: @disorder %>
  <%= ff.hidden_field :user_id, value: current_user.id %>



<br>
<% end %>


  <%= f.submit 'Submit', class: 'form-control' %>

app/views/disorders/edit.html.erb
<h1>Disorders#edit</h1>
<p>Find me in app/views/disorders/edit.html.erb</p>

<%= bootstrap_form_for [current_user, @disorder], url: disorder_path(@disorder) do |f| %>
<%= render 'form', f: f %>
<% end %>

app/views/disorders/index.html.erb
<div class="container">
  <h1>Disorders</h1>
<% @disorders.each do |disorder| %>
<div>
<!-- <p class='disorder'><%#= link_to disorder.name, disorder_user_disorders_path(disorder),  { :class=>"disorder_link" } %></p> -->
<!-- <p><%#= disorder.description %></p> -->

<%# Make this path to the show page, and the show page have a spot to show narratives %>

<p class='disorder'>
  <%= link_to disorder.name, disorder_path(disorder), {  :class => 'disorder_link', :id => disorder.id} %><p id='description<%= disorder.id %>'</p></p>



<% end %>
</div>

app/views/disorders/new.html.erb
<h1>Your Disorder</h1>

<%= bootstrap_form_for @disorder, url: disorders_path do |f| %>
<%= render 'form' %>
<% end %>

app/views/disorders/show.html.erb
<h3><%= @disorder.name %> Stories</h3></div>
<h4>Description<h4>
  <p><%= @disorder.description %></p>

<!-- <h4>Story</h4>
<p><%##= ud.narrative %>
<%# end %> -->

<%= link_to "Edit Disorder", edit_disorder_path(@disorder), class: "btn btn-primary" %>
<%= link_to 'Read Stories', user_disorders_path, class: "btn btn-primary" %></li>