config/routes.rb
Rails.application.routes.draw do
  get 'users/welcome'

resources :therapists

  resources :users, only: [:welcome] do
      resources :user_therapists
  end

root to: 'pages#index'
# 
# match '/user_disorders' => 'user_disorders#create', via: :post
# match '/user_disorders' => 'user_disorders#create', via: :get

get 'current_user' => "users#current_user"



  resources :disorders
  resources :user_therapists
  # resources :disorders, only: [:show] do
  #   resources :user_disorders, only: [:index]
  # end

  resources :treatments
  resources :user_disorders
  resources :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }, skip: [:sessions]
     as :user do
       get 'login' => 'devise/sessions#new', :as => :new_user_session
       post 'login' => 'devise/sessions#create', :as => :user_session
       delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
     end  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/disorder.rb
class Disorder < ApplicationRecord
  has_many :user_disorders
  has_many :user_disorder_treatments, through: :user_disorders
  has_many :users, through: :user_disorders
  has_many :treatments, through: :user_disorder_treatments

  accepts_nested_attributes_for :user_disorders
  validates :name, presence: true

 end

app/models/therapist.rb
class Therapist < ApplicationRecord
  # validates :phone_number, format: { with: /\d{3}-\d{3}-\d{4}/, message: "Format XXX-XXX-XXXX" }

  # has_many :user_therapists
  # has_many :users, through: :user_therapists
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  has_many :user_disorder_treatments
	has_many :user_disorders, through: :user_disorder_treatments

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:github]

  has_many :user_therapists
  has_many :therapists, through: :therapists
  has_many  :user_disorders
  has_many  :user_disorder_treatments, through: :user_disorders
  has_many :disorders, through: :user_disorders


  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.nickname
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/models/user_disorder.rb
class UserDisorder < ApplicationRecord
  belongs_to :user
	belongs_to :disorder
  # belongs_to :user_disorder_treatments

  validates :narrative, presence: true, length: { minimum: 250 }

  accepts_nested_attributes_for :disorder
  scope :filter_by_user, -> (user) { where('user_id = ?', user.id)}
  # scope :by_post_status, -> (post_status) { where('post_status = ?', post_status) }

# # only creating a disorder if it's not already there
#   def disorder_attributes=(disorder_attributes)
#    disorder_attributes.values.each do |disorder_attribute|
#      disorder = Disorder.find_or_create_by(disorder_attribute)
#      self.disorders << disorder
#    end
#  end

end

app/models/user_disorder_treatment.rb
class UserDisorderTreatment < ApplicationRecord
  # belongs_to :user_disorder
	# belongs_to :treatment
end

app/models/user_therapist.rb
class UserTherapist < ApplicationRecord
  belongs_to :user
  before_save :capitalize_fields
  validates :name, presence: true
  validates :location, presence: true 


  scope :location, ->  { order(:location)}

  def capitalize_fields
   location.capitalize!
  end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def welcome
    @user = current_user
    respond_to do |format|
        format.html { render :welcome}
        format.json { render json: @user }
      end
  end

  def show
    @user = User.find(params[:id])

  end

#   def current_user
#     render json: {name: current_user.name}
# end
end

app/helpers/application_helper.rb
require 'navigation_helper.rb'

module ApplicationHelper
      include NavigationHelper

      def errors_for(object)
    if object.errors.any?
        content_tag(:div, class: "panel panel-danger") do
            concat(content_tag(:div, class: "panel-heading") do
                concat(content_tag(:h4, class: "panel-title") do
                    concat "#{pluralize(object.errors.count, "error")} prohibited this #{object.class.name.downcase} from being saved:"
                end)
            end)
            concat(content_tag(:div, class: "panel-body") do
                concat(content_tag(:ul) do
                    object.errors.full_messages.each do |msg|
                        concat content_tag(:li, msg)
                    end
                end)
            end)
        end
    end
end

end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/disorders_helper.rb
module DisordersHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper

  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/not_signed_in_links'
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/therapists_helper.rb
module TherapistsHelper
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/helpers/user_disorders_helper.rb
module UserDisordersHelper
end

app/helpers/user_therapists_helper.rb
module UserTherapistsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/navigation/_collapsible_elements.html.erb
<div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
  <ul class="nav navbar-nav ">
    <%= render collapsible_links_partial_path %>
  </ul>
</div>

app/views/layouts/navigation/_header.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapsible-content" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to 'Women of Trauma', root_path, class: 'navbar-brand' %>
</div>

app/views/layouts/navigation/collapsible_elements/_not_signed_in_links.html.erb
<li ><%= link_to 'Login', login_path %></li>
<li ><%= link_to 'Signup', signup_path %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li class="dropdown comp-menu">
  <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
    <span id="user-name"><%= current_user.name %></span>
    <span class="caret"></span>
  </a>

  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'Welcome', users_welcome_path %></li>
    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
    <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
    <li><%= link_to 'New Disorder', new_user_disorder_path %></li>
    <li><%= link_to 'New Treatment', new_treatment_path %></li>
    <li><%= link_to 'New Therapist', new_user_user_therapist_path(current_user.id) %></li>
    <li><%= link_to 'View Disorders', disorders_path %></li>
    <li><%= link_to 'View Treatments', treatments_path %></li>
    <li><%= link_to 'View Therapists', user_user_therapists_path(current_user.id) %></li>

  </ul>
</li>

<li class="mobile-menu">
  <%= link_to 'Edit Profile', edit_user_registration_path %>
</li>
<li class="mobile-menu">
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
</li>
 <li class="mobile-menu"><%= link_to 'Welcome', users_welcome_path %></li>
<li class="mobile-menu"><%= link_to 'New Disorder', new_user_disorder_path %></li>
<li class="mobile-menu"><%= link_to 'New Treatment', new_treatment_path %></li>
<li class="mobile-menu"><%= link_to 'New Therapist', new_user_user_therapist_path(current_user.id) %></li>
<li class="mobile-menu"><%= link_to 'View Disorders',  disorders_path %></li>
<li class="mobile-menu"><%= link_to 'View Treatments', treatments_path %></li>
<li class="mobile-menu"><%= link_to 'View Therapists', user_user_therapists_path(current_user.id) %></li>