config/routes.rb
Rails.application.routes.draw do
  get 'users/welcome'

resources :therapists

  resources :users, only: [:welcome] do
      resources :user_therapists
  end

root to: 'pages#index'
# 
# match '/user_disorders' => 'user_disorders#create', via: :post
# match '/user_disorders' => 'user_disorders#create', via: :get

get 'current_user' => "users#current_user"



  resources :disorders
  resources :user_therapists
  # resources :disorders, only: [:show] do
  #   resources :user_disorders, only: [:index]
  # end

  resources :treatments
  resources :user_disorders
  resources :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'registrations' }, skip: [:sessions]
     as :user do
       get 'login' => 'devise/sessions#new', :as => :new_user_session
       post 'login' => 'devise/sessions#create', :as => :user_session
       delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
     end  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_disorder.rb
class UserDisorder < ApplicationRecord
  belongs_to :user
	belongs_to :disorder
  # belongs_to :user_disorder_treatments

  validates :narrative, presence: true, length: { minimum: 250 }

  accepts_nested_attributes_for :disorder
  scope :filter_by_user, -> (user) { where('user_id = ?', user.id)}
  # scope :by_post_status, -> (post_status) { where('post_status = ?', post_status) }

# # only creating a disorder if it's not already there
#   def disorder_attributes=(disorder_attributes)
#    disorder_attributes.values.each do |disorder_attribute|
#      disorder = Disorder.find_or_create_by(disorder_attribute)
#      self.disorders << disorder
#    end
#  end

end

app/controllers/user_disorders_controller.rb
class UserDisordersController < ApplicationController

  def index
    @user_disorders = UserDisorder.all
    respond_to do |format|
        format.html { render :index}
        format.json { render json: @user_disorders}
      end
 end

  def new
    @user_disorder = UserDisorder.new
  end

  def create
    @user_disorder = current_user.user_disorders.new(user_disorder_params)
    @user_disorder.save

    respond_to do |format|
        format.html { render :new}
        format.json { render json: @user_disorders }
      end
  end

  def show
    @user_disorder = UserDisorder.find(params[:id])
    if @user_disorder.nil?
      redirect_to disorder_user_disorders_path(@disorder), alert: "Disorder not found"
    end
  else
    @user_disorder = UserDisorder.find(params[:id])
    @user = @user_disorder.user
  end

  private


    def user_disorder_params
      params.require(:user_disorder).permit(:narrative, :user_id, :disorder_id)
    end
end

app/helpers/user_disorders_helper.rb
module UserDisordersHelper
end

app/views/user_disorders/_form.html.erb
<h3>Take Control of Your Narrative</h3>
<%= form_for(@user_disorder) do |f| %>
<%= errors_for(@user_disorder) %>

<label>Choose a Type of Trauma</label>
<%= f.collection_select :disorder_id, Disorder.all, :id, :name, include_blank: false %>

  <label>Your Story:</label><br>
  <%=  f.text_area :narrative, size: "80%x30%" %><br>

  <%= f.submit 'Submit' %>
<% end %>

app/views/user_disorders/_user_disorder.html.erb
<div class="narrative" %>
    <h4>Disorder: <%#= user_disorder.disorder.name %></div>
    <p><%= @user_disorders.each do |ud| %></p>
    <%= ud.narrative %>
    <% end %>
</div>
<br>

<%= link_to 'Create a new narrative', new_disorder_user_disorder_path, class: "btn btn-primary" %>

app/views/user_disorders/edit.html.erb
<h1>Edit Narrative</h1>
<%= render "form" %>

app/views/user_disorders/index.html.erb
<% @user_disorders.each do |d| %>
<h3> Narrative by: <%= link_to d.user.name, user_disorder_path(d, @user) %></h3>
<p>  <%= d.narrative %>
</p>

<% end %>

app/views/user_disorders/new.html.erb
<!-- <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head> -->
  <body>
  <h1>New Narrative</h1>
    <%= render "form" %>
  </body>

app/views/user_disorders/show.html.erb
<h1>UserDisorders#show</h1>
<p>Find me in app/views/user_disorders/show.html.erb</p>
<h1><%=@user_disorder.user.name%>'s Page</h1>
<h2><%= @user_disorder.disorder.name %></h2>
<p><%= @user_disorder.narrative %></p>